# Generated by Django 5.2.6 on 2025-10-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAlias',
        ),
    ]
