# Generated by Django 5.2.6 on 2025-10-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_productalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internal_name',
        ),
    ]
