# Generated by Django 5.2.6 on 2025-10-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tech',
            field=models.CharField(choices=[('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], db_index=True, default='OTR', max_length=3),
        ),
    ]
